source "https://rubygems.org"

ruby "3.4.4"

gem "rails", "~> 8.0.0"

# START_HIGHLIGHT
gem "apnotic"
# END_HIGHLIGHT
gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "jbuilder"
# START_HIGHLIGHT
gem "noticed"
# END_HIGHLIGHT
gem "propshaft"
gem "puma", ">= 5.0"
gem "sqlite3", "~> 2.1"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "web-console"
end
